@URL = http://localhost:62520/api/mails
###
POST {{URL}}
content-type: application/json

{
  "id": 1,
 "to": "aaa.bbb@cccddd.pl",
   "from" : "",
  "title": "Tytuł",
  "body": "Treść"
}
###
GET {{URL}}
