// <auto-generated />
using EmailSenderApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmailSenderApi.Migrations
{
    [DbContext(typeof(MailContext))]
    [Migration("20190405204322_initial 3")]
    partial class initial3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmailSenderApi.Models.Mail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .IsRequired();

                    b.Property<string>("MailFrom")
                        .IsRequired();

                    b.Property<int>("ReciverID");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("ReciverID");

                    b.ToTable("Mails");
                });

            modelBuilder.Entity("EmailSenderApi.Models.Reciver", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MailTo")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Recivers");
                });

            modelBuilder.Entity("EmailSenderApi.Models.Mail", b =>
                {
                    b.HasOne("EmailSenderApi.Models.Reciver", "Reciver")
                        .WithMany()
                        .HasForeignKey("ReciverID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
